config/routes.rb
Rails.application.routes.draw do
  resources :home
  resources :assemblies

  namespace :admin do
    resources :topics
    resources :users
    resources :pre_registrations 
    resources :assemblies do
      collection do
        put ':id/open_close_state', to: 'assemblies#open_close_state'
      end
    end
  end
  root 'home#index'
  devise_for :users

  get '/search_pre_registration', to: 'home#search', as: :search_pre_registration
  
  get 'assemblies/:topic_id/history_votes', to:'assemblies#history_votes', as: :history_votes

  patch 'admin/users/:id/set_paid', to:'admin/users#set_paid', as: :set_paid
  patch 'admin/users/:id/set_not_paid', to:'admin/users#set_not_paid', as: :set_not_paid

  get 'assemblies/:option_id/set_vote', to:'assemblies#set_vote', as: :set_vote

  get 'admin/topics/:id/report', to: 'admin/topics#report', as: :report

  get '/new_user_admin', to: 'admin/users#search', as: :search

end

app/models/assembly.rb
# == Schema Information
#
# Table name: assemblies
#
#  id           :bigint           not null, primary key
#  ata          :string
#  description  :text
#  finish_time  :datetime
#  start_time   :datetime
#  state        :integer
#  title        :string
#  topics_count :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Assembly < ApplicationRecord
    default_scope { order(id: :desc) }

    has_many :topics, dependent: :destroy

    has_rich_text :description

    enum state: [:sketch, :open, :close]

    has_one_attached :ata

    attr_accessor :checkbox_checked

    after_initialize :set_default_state, if: :new_record?

    validates :title, presence: true, uniqueness: true
    validates :start_time, presence: true
    validates :finish_time, presence: true
    validate :finish_time_after_start_time?

    def set_default_state
        self.state ||= :sketch
    end

    def finish_time_after_start_time?
        errors.add :finish_time, I18n.t('finish_time_error') if finish_time && start_time && finish_time < start_time
    end
end

app/controllers/admin/assemblies_controller.rb
class Admin::AssembliesController < AdminController
  before_action :set_assembly, only: [:show, :edit, :update, :destroy, :open_close_state]

  # GET /assemblies
  # GET /assemblies.json
  def index
    @q = Assembly.ransack(params[:q])
    @assemblies = @q.result.page(params[:page]).per(5)
  end

  # GET /assemblies/1
  # GET /assemblies/1.json
  def show
    @max_votes = User.where(paid: true).count
  end

  # GET /assemblies/new
  def new
    @assembly = Assembly.new
  end

  # GET /assemblies/1/edit
  def edit
  end

  # POST /assemblies
  # POST /assemblies.json
  def create
    @assembly = Assembly.new(assembly_params)

    respond_to do |format|
      if @assembly.save
        flash[:success] = Assembly.model_name.human + ' ' + t('success.create')
        format.html { redirect_to admin_assembly_path(@assembly) }
        format.json { render :show, status: :created, location: @assembly }
      else
        format.html { render :new }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assemblies/1
  # PATCH/PUT /assemblies/1.json
  def update
    if params[:assembly][:checkbox_checked] == "1"
      @assembly.update(ata: nil)
    end
    respond_to do |format|
      if @assembly.update(assembly_params)
        flash[:success] = Assembly.model_name.human + ' ' + t('success.update')
        format.html { redirect_to admin_assembly_path(@assembly) }
        format.json { render :show, status: :ok, location: @assembly }
      else
        format.html { render :edit }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assemblies/1
  # DELETE /assemblies/1.json
  def destroy
    @assembly.destroy
    respond_to do |format|
      flash[:success] = Assembly.model_name.human + ' ' + t('success.delete')
      format.html { redirect_to admin_assemblies_path }
      format.json { head :no_content }
    end
  end

  def open_close_state
    @assembly.state == "open" ? @assembly.state = :close : @assembly.state = :open
    if @assembly.save
      render json: { success: true, state: @assembly.state }
    else
      render json: { success: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assembly
      @assembly = Assembly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assembly_params
      params.require(:assembly).permit(:title, :start_time, :finish_time, :description, :state, :topics_count, :ata)
    end
end

app/controllers/assemblies_controller.rb
class AssembliesController < ApplicationController
  layout 'user'
  
  before_action :set_assembly, only: [:show]
  before_action :set_max_votes, only: [:show, :history_votes]
  before_action :authenticate_user!, notice: I18n.t('login_info')

  def index
    @assemblies = Assembly.all
  end

  def show
  end

  def set_vote
    Vote.create!(user_id: current_user.id, option_id: params[:option_id])
    @topic_render = Option.find(params[:option_id]).topic
    @votes_count = @topic_render.sum_votes
  end

  def history_votes
    @topic = Topic.find(params[:topic_id])
    @votes = Vote.includes(:user, :option).where(option_id: [@topic.options.pluck(:id)])
  end

  private

  def set_assembly
    @assembly = Assembly.find(params[:id])
  end

  def set_max_votes
    @max_votes = User.where(paid: true).count
  end
end

app/controllers/user/assemblies_controller.rb
class User::AssembliesController < UserController
  def index
    @assemblies = Assembly.all
  end

  def show
    @assembly = Assembly.find(params[:id])
  end
end

app/helpers/admin/assemblies_helper.rb
module Admin::AssembliesHelper
end

app/helpers/assemblies_helper.rb
module AssembliesHelper
end

app/helpers/user/assemblies_helper.rb
module User::AssembliesHelper
end

app/views/admin/assemblies/_form.html.erb
<%= simple_form_for @assembly, url: url, method: method do |p| %>
  <%= p.input :title, input_html: { class:'w-50 ml-1' } %>
  <%= p.input :start_time, as: :datetime, html5: true, input_html: { class:'w-50' } %>
  <%= p.input :finish_time, as: :datetime, html5: true, input_html: { class:'w-50' } %>
  <%= p.input :ata, as: :file, input_html: { accept:"application/pdf, application/vnd.ms-excel" } %>
  <% if p.object.ata.present? %>
    <%= p.object.ata.blob.filename.sanitized %>
    <%= p.input :checkbox_checked, label: t('remove_ata'), as: :boolean, input_html: { checked: false } %>
  <% end %>
  <%= p.input :description, as: :rich_text_area, input_html: { class: "h-auto" } %>

  <hr>

  <%= p.submit controller.action_name == 'edit' ?
    t('submit.update') + ' ' + Assembly.model_name.human :
    t('submit.create') + ' ' + Assembly.model_name.human,
    class:'btn btn-success' %>
  <%= link_to t('links.cancel'), admin_assemblies_path, class:'btn btn-danger' %>
<% end %>

app/views/admin/assemblies/_options_vote.html.erb
<% topic.options.each do |option| %>
  <hr>
  <div class="row mr-3">
    <div class="col">
      <%= option.description %>
    </div>
    <div calss='col'>
      <%= link_to t('vote'), set_vote_path(option.id), class: "badge badge-pill badge-success p-2",  
        method: :get, remote: true %>
    </div>
  </div>  
<% end %>

app/views/admin/assemblies/_result_votes.html.erb
<% topic.options.each do |option| %>
  <hr>
  <div class="row mr-3">
    <div class="col">
      <%= option.description %>
    </div>
    <div calss='col'>
      <span class="badge badge-pill badge-warning p-2">
        <%= "#{option.percent_votes}%" %>
      </span>
      <span class="badge badge-pill badge-primary p-2">
        <%= option.votes.count %> <%= Vote.model_name.human(count: 2) %>
      </span>
    </div>
  </div>
<% end %>

app/views/admin/assemblies/_search.html.erb
<div class="text-center">
  <%= search_form_for @q, url: admin_assemblies_path, class: 'form-inline d-flex justify-content-center' do |f| %>
    <%= f.search_field :title_cont, placeholder: Assembly.human_attribute_name(:title), class: 'form-control' %>&nbsp;
    <%= f.select(:state_eq, options_for_select(Assembly.states.to_a.map { |w| [t('state.' + w[0]), w[1]] }), { include_blank: t('situation') }, {class: "form-control" }) %>&nbsp;

    <%= f.datetime_field :start_time_gteq, as: :datetime, html5: true, class: 'form-control' %>&nbsp;
    <span><%= t('to') %></span>&nbsp;
    <%= f.datetime_field :finish_time_lteq, as: :datetime, html5: true, class: 'form-control' %>&nbsp;

    <%= f.submit class: 'btn btn-outline-primary' %>&nbsp;
    <%= link_to "&#10799;".html_safe, request.path, class: "font-weight-bold btn btn-outline-secondary" %>
  <% end %>
</div>

app/views/admin/assemblies/_topic.html.erb
<% topic.reload %>
<div class="card">
  <div class="card-header">
    <div class="row text-center align-items-center">
      <div class="col">
        <h5>#<%= topic.title %></h5>
      </div>

      <%= button_to t('vote_history'), history_votes_path(topic.id), class: "btn btn-outline-info
          btn-sm button-history-votes", data: { toggle: "modal", target: "#myModal" }, method: :get, remote: true %>

    </div>
  </div>

  <div class="card-body text-center">
    <h4>
      <strong class="total_votes_<%=topic.id%>"><%= topic.sum_votes %></strong>
      <span class="text-secondary">
        / <%= @max_votes %> <%= Vote.model_name.human(count: 2) %>
      </span>
    </h4>

    <p>
      <%= topic.description %>
    </p>
    <div class='result_text_<%=topic.id%>'>
      <% if (@assembly.start_time <= Time.now && @assembly.finish_time >= Time.now) && 
        !topic.user_voted(current_user.id) && current_user.paid %>
        <% if @assembly.state == 'close' %>
          <%= render 'admin/assemblies/result_votes', topic: topic %>
        <% else %>
          <%= render 'admin/assemblies/options_vote', topic: topic %>
        <% end %>
      <% else %>
        <%= render 'admin/assemblies/result_votes', topic: topic %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/assemblies/edit.html.erb
<h1><%= t('links.edit') + ' ' + Assembly.model_name.human %></h1>

<hr>

<%= render 'form', url: admin_assembly_path, method: :put %>

app/views/admin/assemblies/index.html.erb
<h1>
  <%= Assembly.model_name.human(count: Assembly.all.to_a.length()) %>
  <%= link_to t('links.new'), new_admin_assembly_path, class:"btn btn-primary new" %>
</h1>

<hr>

<%= render 'admin/assemblies/search' %>

<hr>

<p>
  <%= page_entries_info @assemblies %>
</p>

<table class="table table-bordered table-hover">
  <thead class="thead-light">
    <tr>
      <th>#</th>
      <th><%= Assembly.human_attribute_name(:title) %></th>
      <th><%= Assembly.human_attribute_name(:start_time) %></th>
      <th><%= Assembly.human_attribute_name(:finish_time) %></th>
      <th><%= Assembly.human_attribute_name(:state) %></th>
      <th colspan="3"><%= t('actions') %></th>
    </tr>
  </thead>

  <tbody>
    <% @assemblies.each do |assembly| %>
      <tr>
        <td><%= assembly.id %></td>
        <td><%= link_to assembly.title, admin_assembly_path(assembly) %></td>
        <td><%= l(assembly.start_time, format: '%d/%m/%Y - %H:%M') %></td>
        <td><%= l(assembly.finish_time, format: '%d/%m/%Y - %H:%M') %></td>

        <td>
          <% if assembly.state == 'open' %>
            <span class="badge badge-success" id="badge-<%= assembly.id %>"><%= t('state.open') %></span>
          <% elsif assembly.state == 'close' %>
            <span class="badge badge-danger" id="badge-<%= assembly.id %>"><%= t('state.close') %></span>
          <% else %>
            <span class="badge badge-warning" id="badge-<%= assembly.id %>"><%= t('state.sketch') %></span>
          <% end %>
        </td>

        <td>
          <%= button_tag assembly.state == 'open' ? t('links.close') : t('links.open'), class:"btn-open-close #{assembly.state == 'open' ? 'btn btn-outline-danger' : 'btn btn-outline-success'}", id:"assembly-#{assembly.id}" %>
          <%= link_to t('links.edit'), edit_admin_assembly_path(assembly), class:"btn btn-primary" %>
          <%= link_to t('links.delete'), admin_assembly_path(assembly), method: :delete, data: { confirm: t('confirm') }, class:"btn btn-danger" %>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @assemblies %>

app/views/admin/assemblies/new.html.erb
<h1><%= t('links.new') + ' ' + Assembly.model_name.human %></h1>

<hr>

<%= render 'form', url: admin_assemblies_path, method: :post %>

app/views/admin/assemblies/show.html.erb
<h1>
  <%= Assembly.model_name.human %>
  <%= link_to t('links.delete'), admin_assembly_path(@assembly), method: :delete, data: { confirm: t('confirm') }, class:"btn btn-danger new" %>
  <%= link_to t('links.edit'), edit_admin_assembly_path(@assembly), class:"btn btn-primary new" %>
  <%= link_to t('links.back'), admin_assemblies_path, class:"btn btn-secondary new" %>
  <%= link_to t('links.new'), new_admin_assembly_path, class:"btn btn-info new" %>
</h1>

<hr>

<p>
  <strong><%= Assembly.human_attribute_name(:title) %></strong>
  <%= @assembly.title %>
</p>

<p>
  <strong><%= Assembly.human_attribute_name(:start_time) %></strong>
  <%= l(@assembly.start_time, format: '%d/%m/%Y - %H:%M') %>
</p>

<p>
  <strong><%= Assembly.human_attribute_name(:finish_time) %></strong>
  <%= l(@assembly.finish_time, format: '%d/%m/%Y - %H:%M') %>
</p>

<p>
  <strong><%= Assembly.human_attribute_name(:state) %></strong>
  <% if @assembly.state == 'open' %>
    <span class="badge badge-success"><%= t('state.open') %></span>
  <% elsif @assembly.state == 'close' %>
    <span class="badge badge-danger"><%= t('state.close') %></span>
  <% else %>
    <span class="badge badge-warning"><%= t('state.sketch') %></span>
  <% end %>
</p>

<p>
  <strong><%= Assembly.human_attribute_name(:ata) %></strong>
  <% if @assembly.ata.present? %>
    <%= link_to @assembly.ata.blob.filename.sanitized, rails_blob_path(@assembly.ata, disposition: 'attachment') %>
    <%#= @assembly.ata.blob.filename.sanitized %>
  <% else %>
    <%= t('no_ata') %>
  <% end %>
</p>

<p>
  <strong><%= Assembly.human_attribute_name(:description) %></strong>
  <%= @assembly.description %>
</p>

<hr>
<br>

<div class="card">
  <div class="card-body text-center">
    <h2>
      <span class="text-capitalize"><%= t('voting_topics') %></span>
      <%= link_to t('links.new'), new_admin_topic_path, class:"btn btn-primary" %>
    </h2>
  </div>
  <div class="card-body">
    <div class="card-columns">
      <% @assembly.topics.order(:id).includes(:options).each do |topic| %>
        <div id="show_topic_<%= topic.id %>">
          <%= render 'admin/assemblies/topic', topic: topic %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<!-- The Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title"></h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body votes-list"></div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>