config/routes.rb
Rails.application.routes.draw do
  resources :home
  resources :assemblies

  namespace :admin do
    resources :topics
    resources :users
    resources :pre_registrations 
    resources :assemblies do
      collection do
        put ':id/open_close_state', to: 'assemblies#open_close_state'
      end
    end
  end
  root 'home#index'
  devise_for :users

  get '/search_pre_registration', to: 'home#search', as: :search_pre_registration
  
  get 'assemblies/:topic_id/history_votes', to:'assemblies#history_votes', as: :history_votes

  patch 'admin/users/:id/set_paid', to:'admin/users#set_paid', as: :set_paid
  patch 'admin/users/:id/set_not_paid', to:'admin/users#set_not_paid', as: :set_not_paid

  get 'assemblies/:option_id/set_vote', to:'assemblies#set_vote', as: :set_vote

  get 'admin/topics/:id/report', to: 'admin/topics#report', as: :report

  get '/new_user_admin', to: 'admin/users#search', as: :search

end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  assembly_id :bigint           not null
#
# Indexes
#
#  index_topics_on_assembly_id  (assembly_id)
#
# Foreign Keys
#
#  fk_rails_...  (assembly_id => assemblies.id)
#
class Topic < ApplicationRecord
  default_scope { order(id: :desc) }

  belongs_to :assembly, inverse_of: :topics, counter_cache: true
  has_many :options, dependent: :destroy, inverse_of: :topic
  
  accepts_nested_attributes_for :options, reject_if: :all_blank, allow_destroy: true

  has_rich_text :description

  validates :title, presence: true
  validates :description, presence: true
  validates :assembly_id, presence: true

  def sum_votes
    options.map { |option| option.votes.count }.sum
  end

  def user_voted(current_user_id)
    options.map { |option| option.users.exists?(current_user_id) }.include?(true)
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < AdminController
  before_action :set_topic, only: [:show, :edit, :update, :destroy, :report]

  # GET /topics
  # GET /topics.json
  def index
    @q = Topic.ransack(params[:q])
    @topics = @q.result.page(params[:page]).per(5)
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  def report
    @votes = Vote.includes(:user, :option).where(option_id: [@topic.options.pluck(:id)])
    @max_votes = User.where(paid: true).count
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        flash[:success] = Topic.model_name.human + ' ' + t('success.create')
        format.html { redirect_to admin_topic_path(@topic) }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        flash[:success] = Topic.model_name.human + ' ' + t('success.update')
        format.html { redirect_to admin_topic_path(@topic) }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      flash[:success] = Topic.model_name.human + ' ' + t('success.delete')
      format.html { redirect_to admin_topics_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title, :description, :assembly_id, options_attributes: [:id, :description, :_destroy])
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title, :description, :assembly_id)
    end
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/admin/topics/_form.html.erb
<%= simple_form_for @topic, url: url, method: method do |p| %>
  <%= p.input :title, input_html: { class: "w-50" } %>
  <%= p.association :assembly, label: Assembly.model_name.human, label_method: :title, value_method: :id, include_blank: t('select.assembly'), input_html: { class: "w-50" } %>
  <%= p.input :description, as: :rich_text_area, input_html: { class: "h-auto" } %>

  <hr>

  <h3><%= t('options') %></h3>
  
  <hr>

  <div id="options">
    <%= p.simple_fields_for :options do |option| %>
      <%= render 'admin/topics/option_fields', f: option %>
    <% end %>
    <div class="links">
        <%= link_to_add_association t('new_option'), p, :options, class:'btn btn-info btn_option' %>
    </div>
  </div>

  <hr>

  <%= p.submit controller.action_name == 'edit' ?
    t('submit.update') + ' ' + Topic.model_name.human :
    t('submit.create') + ' ' + Topic.model_name.human,
    class:'btn btn-success' %>
  <%= link_to t('links.cancel'), admin_topics_path, class:'btn btn-danger' %>
<% end %>

app/views/admin/topics/_option_fields.html.erb
<div class="nested-fields">
  <%= f.input :description, label: t('title'), input_html: {style: "width: 50%"} %>
  <%= link_to_remove_association t('remove_option'), f, class:'btn btn-danger btn_option' %>
  <hr>
</div>

app/views/admin/topics/_search.html.erb
<div class="text-center">
  <%= search_form_for @q, url: admin_topics_path, class: 'form-inline d-flex justify-content-center' do |f| %>
    <%= f.search_field :title_cont, placeholder: Topic.human_attribute_name(:title), class: 'form-control w-25' %>&nbsp;
    <%= f.select(:assembly_id_eq, options_for_select(Assembly.all.pluck(:title, :id)), { include_blank: t('select.assembly') }, {class: "form-control" }) %>&nbsp;
    <%= f.submit class: 'btn btn-outline-primary' %>&nbsp;
    <%= link_to "&#10799;".html_safe, request.path, class: "font-weight-bold btn btn-outline-secondary" %>
  <% end %>
</div>

app/views/admin/topics/edit.html.erb
<h1><%= t('links.edit') + ' ' + Topic.model_name.human %></h1>

<hr>

<%= render 'form', url: admin_topic_path, method: :put %>

app/views/admin/topics/index.html.erb
<h1>
  <%= Topic.model_name.human(count: Topic.all.to_a.length()) %>
  <%= link_to t('links.new'), new_admin_topic_path, class:"btn btn-primary new" %>
</h1>

<hr>

<%= render 'admin/topics/search' %>

<hr>

<p>
  <%= page_entries_info @topics %>
</p>

<table class="table table-bordered table-hover">
  <thead class="thead-light">
    <tr>
      <th>#</th>
      <th><%= Topic.human_attribute_name(:title) %></th>
      <th><%= Assembly.model_name.human %></th>
      <th><%= Vote.model_name.human(count: 2) %></th>
      <th colspan="3"><%= t('actions') %></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.id %></td>
        <td><%= link_to topic.title, admin_topic_path(topic) %></td>
        <td><%= link_to topic.assembly.title, admin_assembly_path(topic.assembly) %></td>
        <td><%= topic.sum_votes %></td>
        <td>
          <%= link_to t('links.report'), report_path(topic), class:"btn btn-info" %>
          <%= link_to t('links.edit'), edit_admin_topic_path(topic), class:"btn btn-primary" %>
          <%= link_to t('links.delete'), admin_topic_path(topic), method: :delete, data: { confirm: t('confirm') }, class:"btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @topics %>

app/views/admin/topics/new.html.erb
<h1><%= t('links.new') + ' ' + Topic.model_name.human %></h1>

<hr>

<%= render 'form', url: admin_topics_path, method: :post %>

app/views/admin/topics/report.html.erb
<div class="text-center">
  <h1><%= @topic.assembly.title %></h1>
  <h4 class="text-secondary text-center w-75 m-auto" ><%= "#{t('relatory')}: #{@topic.title}" %></h4>
</div>
<br>
<%= render 'assemblies/votes', topic: @topic %>
<hr>
<div class="text-right">
  <%= link_to t('links.back'), admin_topics_path, class:'btn btn-info' %>
</div>

app/views/admin/topics/show.html.erb
<h1>
  <%= Topic.model_name.human %>
  <%= link_to t('links.delete'), admin_topic_path(@topic), method: :delete, data: { confirm: t('confirm') }, class:"btn btn-danger new" %>
  <%= link_to t('links.edit'), edit_admin_topic_path(@topic), class:"btn btn-primary new" %>
  <%= link_to t('links.back'), admin_topics_path, class:"btn btn-secondary new" %>
  <%= link_to t('links.new'), new_admin_topic_path, class:"btn btn-info new" %>
</h1>

<hr>

<p>
  <strong><%= Topic.human_attribute_name(:title) %>:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong><%= Assembly.model_name.human %>:</strong>
  <%= @topic.assembly.title %>
</p>

<p>
  <strong><%= Vote.model_name.human(count: 2) %>:</strong>
  <%= @topic.sum_votes %>
</p>

<p>
  <strong><%= Topic.human_attribute_name(:description) %>:</strong>
  <%= @topic.description %>
</p>

<hr>
<br>

<div class="card">
  <div class="card-body text-center">
    <h2><%= Option.model_name.human(count: 2) %></h2>
  </div>
  <div class="card-body">
    <div class="card-columns">
      <% @topic.options.each do |option| %>
          <div class="card">
            <div class="card-header text-center">
              <h4><%= option.description %></h4>
            </div>
            <h3 class="card-body text-center">
              <strong><%= option.votes.count %></strong>
              <span class="text-secondary">
                <%= Vote.model_name.human(count: option.votes.count) %>
              </span>
            </h3>
          </div>
      <% end %>
    </div>
  </div>
</div>