config/routes.rb
Rails.application.routes.draw do
  resources :home
  resources :assemblies

  namespace :admin do
    resources :topics
    resources :users
    resources :pre_registrations 
    resources :assemblies do
      collection do
        put ':id/open_close_state', to: 'assemblies#open_close_state'
      end
    end
  end
  root 'home#index'
  devise_for :users

  get '/search_pre_registration', to: 'home#search', as: :search_pre_registration
  
  get 'assemblies/:topic_id/history_votes', to:'assemblies#history_votes', as: :history_votes

  patch 'admin/users/:id/set_paid', to:'admin/users#set_paid', as: :set_paid
  patch 'admin/users/:id/set_not_paid', to:'admin/users#set_not_paid', as: :set_not_paid

  get 'assemblies/:option_id/set_vote', to:'assemblies#set_vote', as: :set_vote

  get 'admin/topics/:id/report', to: 'admin/topics#report', as: :report

  get '/new_user_admin', to: 'admin/users#search', as: :search

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  ap                     :integer
#  bloc                   :integer
#  cpf                    :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  paid                   :boolean          default(TRUE)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :integer
#  user_name              :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  pre_registration_id    :bigint           not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_pre_registration_id   (pre_registration_id)
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (pre_registration_id => pre_registrations.id)
#
class User < ApplicationRecord
  default_scope { order(id: :desc) }
  
  belongs_to :pre_registration

  has_many :votes, dependent: :destroy
  has_many :options, through: :votes

  enum role: [:user, :admin]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_initialize :set_default_role, if: :new_record?

  validates :user_name, presence: true
  validates :cpf, presence: true, uniqueness: true
  validates :bloc, presence: true
  validates :ap, presence: true
  validates :pre_registration_id, presence: true, uniqueness: true

  def set_default_role
    self.role ||= :user
  end

  def self.create_with_password(attr={})
    generated_password = "123456"
    self.new(attr.merge(password: generated_password, password_confirmation: generated_password))
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :set_paid, :set_not_paid]
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page]).per(5)
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create_with_password(user_params)
    respond_to do |format|
      if @user.save
        flash[:success] = User.model_name.human + ' ' + t('success.create')
        format.html { redirect_to admin_user_path(@user) }
        format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:success] = User.model_name.human + ' ' + t('success.update')
        format.html { redirect_to admin_user_path(@user) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      flash[:success] = User.model_name.human + ' ' + t('success.delete')
      format.html { redirect_to admin_users_path }
      format.json { head :no_content }
    end
  end

  def set_paid
    @user.update(paid: true)
    redirect_to admin_users_path
  end

  def set_not_paid
    @user.update(paid: false)
    redirect_to admin_users_path
  end

  def search
    data = PreRegistration.find(params[:id])
    if(data.present?)
      render json: {
        id: data.id, cpf: data.cpf, bloc: data.bloc, ap: data.ap 
      }
    else
      render json: { error: true}
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation, :pre_registration_id, :role, :paid, :cpf, :ap, :bloc)
  end

end

app/controllers/user/assemblies_controller.rb
class User::AssembliesController < UserController
  def index
    @assemblies = Assembly.all
  end

  def show
    @assembly = Assembly.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/assemblies_helper.rb
module User::AssembliesHelper
end

app/helpers/user/home_helper.rb
module User::HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/_form.html.erb
<%= simple_form_for @user, url: url, method: method  do |p| %>
  <div class="form-group ">
    <%= p.association :pre_registration, label: PreRegistration.model_name.human, label_method: :cpf, 
        input_html: {class:'new-user-admin w-50'},value_method: :id, include_blank: t('select.cpf') %>
  
    <label for="cpf"><%= PreRegistration.human_attribute_name('cpf') %></label>
    <input disabled type='text' class='search_cpf form-control w-50' id="cpf"><br>

    <label for="bloc"><%= PreRegistration.human_attribute_name('bloc') %></label>
    <input disabled type='text' class='search_bloc form-control w-50' id="bloc"><br>
          
    <label for="ap"><%= PreRegistration.human_attribute_name('ap') %></label>
    <input disabled type='text' class='search_ap form-control w-50' id="ap"><br>

    <%= p.hidden_field :cpf ,class:'search_cpf form-control' %>
    <%= p.hidden_field :bloc, class:'search_bloc form-control' %>
    <%= p.hidden_field :ap, class:'search_ap form-control' %>
    <%= p.input :user_name, input_html: {class:"form-control w-50"} %>
    <%= p.input :email, input_html: {class:"form-control w-50"} %>
    <%= p.input :role, collection: User.roles.keys.map {|role| [role.titleize,role]}, include_blank: false, input_html: {class:"form-control w-50"} %>
  </div>  
  <hr>

  <div>
    <%= p.submit controller.action_name == 'edit' ?
      t('submit.update') + ' ' + User.model_name.human :
      t('submit.create') + ' ' + User.model_name.human,
      class:'btn btn-success' %>
    <%= link_to t('links.cancel'), admin_users_path, class:'btn btn-danger' %>
  </div>
<% end %>

app/views/admin/users/_search.html.erb
<div class="text-center">
  <%= search_form_for @q, url: admin_users_path, class: 'form-inline d-flex justify-content-center' do |f| %>
    <%= f.search_field :user_name_cont, placeholder: User.human_attribute_name(:user_name), class: 'form-control w-25' %>&nbsp;
    <%= f.search_field :cpf_cont, placeholder: PreRegistration.human_attribute_name(:cpf), class: 'form-control' %>&nbsp;
    <%= f.select(:paid_eq, options_for_select([[t('yes'), true], [t('no'), false]].map { | w | [w[0].humanize, w[1]] }), { include_blank: t('select.type') }, {class: "form-control" }) %>&nbsp;
    <%= f.select(:bloc_eq, options_for_select(PreRegistration::BLOC), { include_blank: t('select.bloc') }, {class: "form-control" }) %>&nbsp;
    <%= f.select(:ap_eq, options_for_select(PreRegistration::AP), { include_blank: t('select.ap') }, {class: "form-control" }) %>&nbsp;
    <%= f.submit class: 'btn btn-outline-primary' %>&nbsp;
    <%= link_to "&#10799;".html_safe, request.path, class: "font-weight-bold btn btn-outline-secondary" %>
  <% end %>
</div>

app/views/admin/users/edit.html.erb
<h1><%= t('links.edit') + ' ' + User.model_name.human %></h1>

<hr>

<%= render 'form', url: admin_user_path, method: :put %>

app/views/admin/users/index.html.erb
<h1>
  <%= User.model_name.human(count: User.all.to_a.length()) %>
  <%= link_to t('links.new'), new_admin_user_path, class:"btn btn-primary new" %>
</h1>

<hr>

<%= render 'admin/users/search' %>

<hr>

<p>
  <%= page_entries_info @users %>
</p>

<table class="table table-bordered table-hover">
  <thead class="thead-light">
    <tr>
      <th>#</th>
      <th><%= User.human_attribute_name(:user_name) %></th>
      <th><%= PreRegistration.human_attribute_name(:cpf) %></th>
      <th><%= PreRegistration.human_attribute_name(:bloc) %></th>
      <th><%= PreRegistration.human_attribute_name(:ap) %></th>
      <th><%= User.human_attribute_name(:role) %></th>
      <th><%= User.human_attribute_name(:paid) %></th>
      <th colspan="3"><%= t('actions') %></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.user_name, admin_user_path(user) %></td>
        <td><%= user.cpf %></td>
        <td><%= user.bloc %></td>
        <td><%= user.ap %></td>
        <td><%= user.role %></td>
        <td>
          <% if (user.paid) ? @class_name = 'badge badge-success' : @class_name = 'badge badge-danger'%><% end %>
          <span class="<%= @class_name %>">
            <%= user.paid ? t('yes') : t('no') %>
          </span>
        </td>
        <td>
          <%if user.paid?%>
            <%= link_to t('links.block'), set_not_paid_path(user), method: :patch, class:"btn btn-outline-danger" %>
          <%else%>  
            <%= link_to t('links.release'), set_paid_path(user), method: :patch, class:"btn btn-outline-success" %>
          <% end %>
          <%= link_to t('links.edit'), edit_admin_user_path(user), class:'btn btn-primary'%>
          <%= link_to t('links.delete'), admin_user_path(user), method: :delete, data: { confirm: t('confirm') }, class:'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/admin/users/new.html.erb
<h1><%= t('links.new') + ' ' + User.model_name.human %></h1>

<hr>

<%= render 'form', url: admin_users_path, method: :post %>

app/views/admin/users/show.html.erb
<h1>
  <%= User.model_name.human %>
</h1>

<hr>

<p>
  <strong><%= User.human_attribute_name(:user_name) %>:</strong>
  <%= @user.user_name %>
</p>

<p>
  <strong><%= PreRegistration.human_attribute_name(:cpf) %>:</strong>
  <%= @user.cpf %>
</p>

<p>
  <strong><%= PreRegistration.human_attribute_name(:bloc) %>:</strong>
  <%= @user.bloc %>
</p>

<p>
  <strong><%= PreRegistration.human_attribute_name(:ap) %>:</strong>
  <%= @user.ap %>
</p>

<p>
  <strong><%= User.human_attribute_name(:role) %>:</strong>
  <%= @user.role %>
</p>

<p>
  <strong><%= User.human_attribute_name(:paid) %>:</strong>
  <% if (@user.paid) ? @class_name = 'badge badge-success' : @class_name = 'badge badge-danger'%><% end %>
  <span class="<%= @class_name %>">
    <%= @user.paid ? t('yes') : t('no') %>
  </span>
</p>

<%= link_to t('links.back'), admin_users_path, class:"btn btn-primary" %>