config/routes.rb
Rails.application.routes.draw do
  resources :home
  resources :assemblies

  namespace :admin do
    resources :topics
    resources :users
    resources :pre_registrations 
    resources :assemblies do
      collection do
        put ':id/open_close_state', to: 'assemblies#open_close_state'
      end
    end
  end
  root 'home#index'
  devise_for :users

  get '/search_pre_registration', to: 'home#search', as: :search_pre_registration
  
  get 'assemblies/:topic_id/history_votes', to:'assemblies#history_votes', as: :history_votes

  patch 'admin/users/:id/set_paid', to:'admin/users#set_paid', as: :set_paid
  patch 'admin/users/:id/set_not_paid', to:'admin/users#set_not_paid', as: :set_not_paid

  get 'assemblies/:option_id/set_vote', to:'assemblies#set_vote', as: :set_vote

  get 'admin/topics/:id/report', to: 'admin/topics#report', as: :report

  get '/new_user_admin', to: 'admin/users#search', as: :search

end

app/views/layouts/_admin_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#"><%= Assembly.model_name.human %> Admin</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item <%= 'active' if current_page? controller: :assemblies %>">
            <%= link_to Assembly.model_name.human(count: 2), admin_assemblies_path, class:'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if current_page? controller: :topics %>">
            <%= link_to Topic.model_name.human(count: 2), admin_topics_path, class:'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if current_page? controller: :users %>">
            <%= link_to User.model_name.human(count: 2), admin_users_path, class:'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if current_page? controller: :pre_registrations %>">
            <%= link_to PreRegistration.model_name.human(count: 2), admin_pre_registrations_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t('links.home'), home_index_path, class:'nav-link' %>
          </li>
          <li class="hello-user nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              <%= t('hello') + ', ' + current_user.user_name %>
            </a>
            <div class="dropdown-menu">
              <%= link_to t('links.edit'), edit_user_registration_path, class:'dropdown-item' %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to t('logout'), destroy_user_session_path, method: :delete, data: { confirm: t('confirm') }, class:'btn btn-danger ml-3' %>
          </li>
        </ul>
      </div>
    </div>
</nav>

app/views/layouts/_footer.html.erb
<footer class="py-5">
  <div class="container">
    <p class="m-0 text-center">Copyright &copy; CavernaLabs 2020</p>
  </div>
</footer>

app/views/layouts/_notice.html.erb
<% flash.each do |key, value| %>
  <div id="notice" class="alert <%= flash_class(key) %> alert-dismissible">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_user_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top user-navbar">
  <div class="container">
    <a class="navbar-brand" href="#"><%= Assembly.model_name.human %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item <%= 'active' if controller_name == "home" %>">
          <%= link_to t('links.home'), home_index_path, class:'nav-link' %>
        </li>
        <li class="nav-item <%= 'active' if controller_name == "assemblies" %>">
          <%= link_to Assembly.model_name.human(count: 2), assemblies_path, class:'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <% if current_user.role == 'admin' %>
            <li class="nav-item">
              <%= link_to t('Admin'), admin_assemblies_path, class:'nav-link' %>
            </li>
          <% end %>
          <li class="hello-user nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
              <%= t('hello') + ', ' + current_user.user_name %>
            </a>
            <div class="dropdown-menu">
              <%= link_to t('links.edit'), edit_user_registration_path, class:'dropdown-item' %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to t('logout'), destroy_user_session_path, method: :delete, data: { confirm: t('confirm') }, class:'btn btn-danger ml-3' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to t('login'), new_user_session_path, class:'btn btn-success ml-3' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assembleia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'small-business' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/admin_nav" %>
    <div class="container">
      <%= render 'layouts/notice' %>
      <%= yield %>  
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assembleia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assembleia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'small-business' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/user_nav" %>
    <div class="container">
      <%= render 'layouts/notice' %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>